name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Create empty .env
        run: touch .env

      - name: Run jest
        run: npm test -- --coverage
        env:
          YOOMONEY_TOKEN: ${{ secrets.YOOMONEY_TOKEN }}
          YOOMONEY_WALLET: ${{ secrets.YOOMONEY_WALLET }}

      - name: Upload coverage
        run: npx codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
